PACKAGES = "${PN} dpkg libdpkg-perl"
PROVIDES = "dpkg libdpkg-perl"
SRC_URI = " \
	http://ftp.de.debian.org/debian/pool/main/d/dpkg/dpkg_1.19.7_armhf.deb;unpack=0;name=deb0\
	http://ftp.de.debian.org/debian/pool/main/d/dpkg/libdpkg-perl_1.19.7_all.deb;unpack=0;name=deb1\
"
DEBFILENAME_dpkg = "dpkg_1.19.7_armhf.deb"
SRC_URI[deb0.sha256sum] = "275e2938c26fb863c28ce7d346c4e79d4b58995d20ed09e79201d7a2374ff994"
SRC_URI[deb0.md5sum] = "6863b2f7a75bdc3b23a2af38b7f383d1"
DEBFILENAME_libdpkg-perl = "libdpkg-perl_1.19.7_all.deb"
SRC_URI[deb1.sha256sum] = "1cb272a8168138e9b8334e87cc26388259f232b74667b3a7f3856f227adcc4ba"
SRC_URI[deb1.md5sum] = "a48ac7ead97ef1bf1979bf904031463d"

RDEPENDS_${PN} = "libbz2-1.0 libc6 (>= 2.28) liblzma5 (>= 5.2.2) libselinux1 (>= 2.3) tar (>= 1.28-1) zlib1g (>= 1:1.1.4)"
RDEPENDS_lib${PN}-perl = "dpkg (>= 1.18.11) perl"

inherit deb_group

FILES_${PN} = " \
    ./etc/alternatives/README \
    ./etc/cron.daily/dpkg \
    ./etc/dpkg/dpkg.cfg \
    ./etc/logrotate.d/alternatives \
    ./etc/logrotate.d/dpkg \
    ./sbin/start-stop-daemon \
    ./usr/bin/dpkg \
    ./usr/bin/dpkg-deb \
    ./usr/bin/dpkg-divert \
    ./usr/bin/dpkg-maintscript-helper \
    ./usr/bin/dpkg-query \
    ./usr/bin/dpkg-split \
    ./usr/bin/dpkg-statoverride \
    ./usr/bin/dpkg-trigger \
    ./usr/bin/update-alternatives \
    ./usr/share/bug/dpkg \
    ./usr/share/doc/dpkg/AUTHORS \
    ./usr/share/doc/dpkg/README.feature-removal-schedule.gz \
    ./usr/share/doc/dpkg/THANKS.gz \
    ./usr/share/doc/dpkg/changelog.Debian.gz \
    ./usr/share/doc/dpkg/changelog.gz \
    ./usr/share/doc/dpkg/copyright \
    ./usr/share/doc/dpkg/usertags.gz \
    ./usr/share/dpkg/abitable \
    ./usr/share/dpkg/cputable \
    ./usr/share/dpkg/ostable \
    ./usr/share/dpkg/tupletable \
    ./usr/share/lintian/overrides/dpkg \
    ./usr/share/lintian/profiles/dpkg/main.profile \
    ./usr/share/locale/ast/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/bs/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/ca/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/cs/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/da/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/de/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/dz/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/el/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/eo/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/es/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/et/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/eu/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/fr/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/gl/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/hu/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/id/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/it/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/ja/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/km/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/ko/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/ku/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/lt/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/mr/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/nb/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/ne/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/nl/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/nn/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/pa/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/pl/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/pt/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/pt_BR/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/ro/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/ru/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/sk/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/sv/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/th/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/tl/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/tr/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/vi/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/zh_CN/LC_MESSAGES/dpkg.mo \
    ./usr/share/locale/zh_TW/LC_MESSAGES/dpkg.mo \
    ./usr/share/man/de/man1/dpkg-deb.1.gz \
    ./usr/share/man/de/man1/dpkg-divert.1.gz \
    ./usr/share/man/de/man1/dpkg-maintscript-helper.1.gz \
    ./usr/share/man/de/man1/dpkg-query.1.gz \
    ./usr/share/man/de/man1/dpkg-split.1.gz \
    ./usr/share/man/de/man1/dpkg-statoverride.1.gz \
    ./usr/share/man/de/man1/dpkg-trigger.1.gz \
    ./usr/share/man/de/man1/dpkg.1.gz \
    ./usr/share/man/de/man1/update-alternatives.1.gz \
    ./usr/share/man/de/man5/dpkg.cfg.5.gz \
    ./usr/share/man/de/man8/start-stop-daemon.8.gz \
    ./usr/share/man/es/man1/dpkg-split.1.gz \
    ./usr/share/man/es/man1/update-alternatives.1.gz \
    ./usr/share/man/fr/man1/dpkg-deb.1.gz \
    ./usr/share/man/fr/man1/dpkg-divert.1.gz \
    ./usr/share/man/fr/man1/dpkg-maintscript-helper.1.gz \
    ./usr/share/man/fr/man1/dpkg-query.1.gz \
    ./usr/share/man/fr/man1/dpkg-split.1.gz \
    ./usr/share/man/fr/man1/dpkg-statoverride.1.gz \
    ./usr/share/man/fr/man1/dpkg-trigger.1.gz \
    ./usr/share/man/fr/man1/dpkg.1.gz \
    ./usr/share/man/fr/man1/update-alternatives.1.gz \
    ./usr/share/man/fr/man5/dpkg.cfg.5.gz \
    ./usr/share/man/fr/man8/start-stop-daemon.8.gz \
    ./usr/share/man/it/man1/dpkg-maintscript-helper.1.gz \
    ./usr/share/man/it/man1/dpkg-split.1.gz \
    ./usr/share/man/it/man1/update-alternatives.1.gz \
    ./usr/share/man/ja/man1/dpkg-split.1.gz \
    ./usr/share/man/ja/man1/update-alternatives.1.gz \
    ./usr/share/man/man1/dpkg-deb.1.gz \
    ./usr/share/man/man1/dpkg-divert.1.gz \
    ./usr/share/man/man1/dpkg-maintscript-helper.1.gz \
    ./usr/share/man/man1/dpkg-query.1.gz \
    ./usr/share/man/man1/dpkg-split.1.gz \
    ./usr/share/man/man1/dpkg-statoverride.1.gz \
    ./usr/share/man/man1/dpkg-trigger.1.gz \
    ./usr/share/man/man1/dpkg.1.gz \
    ./usr/share/man/man1/update-alternatives.1.gz \
    ./usr/share/man/man5/dpkg.cfg.5.gz \
    ./usr/share/man/man8/start-stop-daemon.8.gz \
    ./usr/share/man/nl/man1/dpkg-deb.1.gz \
    ./usr/share/man/nl/man1/dpkg-divert.1.gz \
    ./usr/share/man/nl/man1/dpkg-maintscript-helper.1.gz \
    ./usr/share/man/nl/man1/dpkg-query.1.gz \
    ./usr/share/man/nl/man1/dpkg-split.1.gz \
    ./usr/share/man/nl/man1/dpkg-statoverride.1.gz \
    ./usr/share/man/nl/man1/dpkg-trigger.1.gz \
    ./usr/share/man/nl/man1/dpkg.1.gz \
    ./usr/share/man/nl/man1/update-alternatives.1.gz \
    ./usr/share/man/nl/man5/dpkg.cfg.5.gz \
    ./usr/share/man/nl/man8/start-stop-daemon.8.gz \
    ./usr/share/man/pl/man1/dpkg-split.1.gz \
    ./usr/share/man/pl/man1/update-alternatives.1.gz \
    ./usr/share/man/sv/man1/dpkg-maintscript-helper.1.gz \
    ./usr/share/man/sv/man1/dpkg-split.1.gz \
    ./usr/share/man/sv/man1/dpkg-trigger.1.gz \
    ./usr/share/man/sv/man1/update-alternatives.1.gz \
    ./usr/share/polkit-1/actions/org.dpkg.pkexec.update-alternatives.policy\
"
FILES_libdpkg-perl = " \
    ./usr/share/bug/libdpkg-perl \
    ./usr/share/doc/libdpkg-perl/AUTHORS \
    ./usr/share/doc/libdpkg-perl/README.api \
    ./usr/share/doc/libdpkg-perl/README.feature-removal-schedule.gz \
    ./usr/share/doc/libdpkg-perl/THANKS.gz \
    ./usr/share/doc/libdpkg-perl/changelog.Debian.gz \
    ./usr/share/doc/libdpkg-perl/changelog.gz \
    ./usr/share/doc/libdpkg-perl/copyright \
    ./usr/share/doc/libdpkg-perl/usertags.gz \
    ./usr/share/dpkg/no-pie-compile.specs \
    ./usr/share/dpkg/no-pie-link.specs \
    ./usr/share/dpkg/pie-compile.specs \
    ./usr/share/dpkg/pie-link.specs \
    ./usr/share/locale/ca/LC_MESSAGES/dpkg-dev.mo \
    ./usr/share/locale/de/LC_MESSAGES/dpkg-dev.mo \
    ./usr/share/locale/es/LC_MESSAGES/dpkg-dev.mo \
    ./usr/share/locale/fr/LC_MESSAGES/dpkg-dev.mo \
    ./usr/share/locale/pl/LC_MESSAGES/dpkg-dev.mo \
    ./usr/share/locale/ru/LC_MESSAGES/dpkg-dev.mo \
    ./usr/share/locale/sv/LC_MESSAGES/dpkg-dev.mo \
    ./usr/share/man/man3/Dpkg.3perl.gz \
    ./usr/share/man/man3/Dpkg::Arch.3perl.gz \
    ./usr/share/man/man3/Dpkg::Build::Env.3perl.gz \
    ./usr/share/man/man3/Dpkg::Build::Info.3perl.gz \
    ./usr/share/man/man3/Dpkg::Build::Types.3perl.gz \
    ./usr/share/man/man3/Dpkg::BuildFlags.3perl.gz \
    ./usr/share/man/man3/Dpkg::BuildOptions.3perl.gz \
    ./usr/share/man/man3/Dpkg::BuildProfiles.3perl.gz \
    ./usr/share/man/man3/Dpkg::Changelog.3perl.gz \
    ./usr/share/man/man3/Dpkg::Changelog::Debian.3perl.gz \
    ./usr/share/man/man3/Dpkg::Changelog::Entry.3perl.gz \
    ./usr/share/man/man3/Dpkg::Changelog::Entry::Debian.3perl.gz \
    ./usr/share/man/man3/Dpkg::Changelog::Parse.3perl.gz \
    ./usr/share/man/man3/Dpkg::Checksums.3perl.gz \
    ./usr/share/man/man3/Dpkg::Compression.3perl.gz \
    ./usr/share/man/man3/Dpkg::Compression::FileHandle.3perl.gz \
    ./usr/share/man/man3/Dpkg::Compression::Process.3perl.gz \
    ./usr/share/man/man3/Dpkg::Conf.3perl.gz \
    ./usr/share/man/man3/Dpkg::Control.3perl.gz \
    ./usr/share/man/man3/Dpkg::Control::Changelog.3perl.gz \
    ./usr/share/man/man3/Dpkg::Control::Fields.3perl.gz \
    ./usr/share/man/man3/Dpkg::Control::FieldsCore.3perl.gz \
    ./usr/share/man/man3/Dpkg::Control::Hash.3perl.gz \
    ./usr/share/man/man3/Dpkg::Control::HashCore.3perl.gz \
    ./usr/share/man/man3/Dpkg::Control::Info.3perl.gz \
    ./usr/share/man/man3/Dpkg::Control::Tests.3perl.gz \
    ./usr/share/man/man3/Dpkg::Control::Tests::Entry.3perl.gz \
    ./usr/share/man/man3/Dpkg::Control::Types.3perl.gz \
    ./usr/share/man/man3/Dpkg::Deps.3perl.gz \
    ./usr/share/man/man3/Dpkg::Deps::AND.3perl.gz \
    ./usr/share/man/man3/Dpkg::Deps::KnownFacts.3perl.gz \
    ./usr/share/man/man3/Dpkg::Deps::Multiple.3perl.gz \
    ./usr/share/man/man3/Dpkg::Deps::OR.3perl.gz \
    ./usr/share/man/man3/Dpkg::Deps::Simple.3perl.gz \
    ./usr/share/man/man3/Dpkg::Deps::Union.3perl.gz \
    ./usr/share/man/man3/Dpkg::Exit.3perl.gz \
    ./usr/share/man/man3/Dpkg::Gettext.3perl.gz \
    ./usr/share/man/man3/Dpkg::IPC.3perl.gz \
    ./usr/share/man/man3/Dpkg::Index.3perl.gz \
    ./usr/share/man/man3/Dpkg::Interface::Storable.3perl.gz \
    ./usr/share/man/man3/Dpkg::Path.3perl.gz \
    ./usr/share/man/man3/Dpkg::Source::Format.3perl.gz \
    ./usr/share/man/man3/Dpkg::Source::Package.3perl.gz \
    ./usr/share/man/man3/Dpkg::Substvars.3perl.gz \
    ./usr/share/man/man3/Dpkg::Vendor.3perl.gz \
    ./usr/share/man/man3/Dpkg::Vendor::Debian.3perl.gz \
    ./usr/share/man/man3/Dpkg::Vendor::Default.3perl.gz \
    ./usr/share/man/man3/Dpkg::Vendor::Ubuntu.3perl.gz \
    ./usr/share/man/man3/Dpkg::Version.3perl.gz \
    ./usr/share/perl5/Dpkg.pm \
    ./usr/share/perl5/Dpkg/Arch.pm \
    ./usr/share/perl5/Dpkg/Build/Env.pm \
    ./usr/share/perl5/Dpkg/Build/Info.pm \
    ./usr/share/perl5/Dpkg/Build/Types.pm \
    ./usr/share/perl5/Dpkg/BuildFlags.pm \
    ./usr/share/perl5/Dpkg/BuildOptions.pm \
    ./usr/share/perl5/Dpkg/BuildProfiles.pm \
    ./usr/share/perl5/Dpkg/Changelog.pm \
    ./usr/share/perl5/Dpkg/Changelog/Debian.pm \
    ./usr/share/perl5/Dpkg/Changelog/Entry.pm \
    ./usr/share/perl5/Dpkg/Changelog/Entry/Debian.pm \
    ./usr/share/perl5/Dpkg/Changelog/Parse.pm \
    ./usr/share/perl5/Dpkg/Checksums.pm \
    ./usr/share/perl5/Dpkg/Compression.pm \
    ./usr/share/perl5/Dpkg/Compression/FileHandle.pm \
    ./usr/share/perl5/Dpkg/Compression/Process.pm \
    ./usr/share/perl5/Dpkg/Conf.pm \
    ./usr/share/perl5/Dpkg/Control.pm \
    ./usr/share/perl5/Dpkg/Control/Changelog.pm \
    ./usr/share/perl5/Dpkg/Control/Fields.pm \
    ./usr/share/perl5/Dpkg/Control/FieldsCore.pm \
    ./usr/share/perl5/Dpkg/Control/Hash.pm \
    ./usr/share/perl5/Dpkg/Control/HashCore.pm \
    ./usr/share/perl5/Dpkg/Control/Info.pm \
    ./usr/share/perl5/Dpkg/Control/Tests.pm \
    ./usr/share/perl5/Dpkg/Control/Tests/Entry.pm \
    ./usr/share/perl5/Dpkg/Control/Types.pm \
    ./usr/share/perl5/Dpkg/Deps.pm \
    ./usr/share/perl5/Dpkg/Deps/AND.pm \
    ./usr/share/perl5/Dpkg/Deps/KnownFacts.pm \
    ./usr/share/perl5/Dpkg/Deps/Multiple.pm \
    ./usr/share/perl5/Dpkg/Deps/OR.pm \
    ./usr/share/perl5/Dpkg/Deps/Simple.pm \
    ./usr/share/perl5/Dpkg/Deps/Union.pm \
    ./usr/share/perl5/Dpkg/Dist/Files.pm \
    ./usr/share/perl5/Dpkg/ErrorHandling.pm \
    ./usr/share/perl5/Dpkg/Exit.pm \
    ./usr/share/perl5/Dpkg/File.pm \
    ./usr/share/perl5/Dpkg/Getopt.pm \
    ./usr/share/perl5/Dpkg/Gettext.pm \
    ./usr/share/perl5/Dpkg/IPC.pm \
    ./usr/share/perl5/Dpkg/Index.pm \
    ./usr/share/perl5/Dpkg/Interface/Storable.pm \
    ./usr/share/perl5/Dpkg/Lock.pm \
    ./usr/share/perl5/Dpkg/OpenPGP.pm \
    ./usr/share/perl5/Dpkg/Package.pm \
    ./usr/share/perl5/Dpkg/Path.pm \
    ./usr/share/perl5/Dpkg/Shlibs.pm \
    ./usr/share/perl5/Dpkg/Shlibs/Cppfilt.pm \
    ./usr/share/perl5/Dpkg/Shlibs/Objdump.pm \
    ./usr/share/perl5/Dpkg/Shlibs/Symbol.pm \
    ./usr/share/perl5/Dpkg/Shlibs/SymbolFile.pm \
    ./usr/share/perl5/Dpkg/Source/Archive.pm \
    ./usr/share/perl5/Dpkg/Source/BinaryFiles.pm \
    ./usr/share/perl5/Dpkg/Source/Format.pm \
    ./usr/share/perl5/Dpkg/Source/Functions.pm \
    ./usr/share/perl5/Dpkg/Source/Package.pm \
    ./usr/share/perl5/Dpkg/Source/Package/V1.pm \
    ./usr/share/perl5/Dpkg/Source/Package/V2.pm \
    ./usr/share/perl5/Dpkg/Source/Package/V3/Bzr.pm \
    ./usr/share/perl5/Dpkg/Source/Package/V3/Custom.pm \
    ./usr/share/perl5/Dpkg/Source/Package/V3/Git.pm \
    ./usr/share/perl5/Dpkg/Source/Package/V3/Native.pm \
    ./usr/share/perl5/Dpkg/Source/Package/V3/Quilt.pm \
    ./usr/share/perl5/Dpkg/Source/Patch.pm \
    ./usr/share/perl5/Dpkg/Source/Quilt.pm \
    ./usr/share/perl5/Dpkg/Substvars.pm \
    ./usr/share/perl5/Dpkg/Vars.pm \
    ./usr/share/perl5/Dpkg/Vendor.pm \
    ./usr/share/perl5/Dpkg/Vendor/Debian.pm \
    ./usr/share/perl5/Dpkg/Vendor/Default.pm \
    ./usr/share/perl5/Dpkg/Vendor/Ubuntu.pm \
    ./usr/share/perl5/Dpkg/Version.pm\
"
