PACKAGES = "${PN} libglib2.0-0 libglib2.0-bin libglib2.0-data libglib2.0-dev libglib2.0-dev-bin"
PROVIDES = "libglib2.0-0 libglib2.0-bin libglib2.0-data libglib2.0-dev libglib2.0-dev-bin"
SRC_URI = " \
	http://ftp.de.debian.org/debian/pool/main/g/glib2.0/libglib2.0-0_2.58.3-2+deb10u3_armhf.deb;unpack=0;name=deb0\
	http://ftp.de.debian.org/debian/pool/main/g/glib2.0/libglib2.0-bin_2.58.3-2+deb10u3_armhf.deb;unpack=0;name=deb1\
	http://ftp.de.debian.org/debian/pool/main/g/glib2.0/libglib2.0-data_2.58.3-2+deb10u3_all.deb;unpack=0;name=deb2\
	http://ftp.de.debian.org/debian/pool/main/g/glib2.0/libglib2.0-dev_2.58.3-2+deb10u3_armhf.deb;unpack=0;name=deb3\
	http://ftp.de.debian.org/debian/pool/main/g/glib2.0/libglib2.0-dev-bin_2.58.3-2+deb10u3_armhf.deb;unpack=0;name=deb4\
"
DEBFILENAME_libglib2.0-0 = "libglib2.0-0_2.58.3-2+deb10u3_armhf.deb"
SRC_URI[deb0.sha256sum] = "6f5fad608614e25f54a301b63dfd3677b566b132df7d74dfca103863fd15c8e8"
SRC_URI[deb0.md5sum] = "08bb4838b38f1230d8cc5ee34dcac75c"
DEBFILENAME_libglib2.0-bin = "libglib2.0-bin_2.58.3-2+deb10u3_armhf.deb"
SRC_URI[deb1.sha256sum] = "a1c845069c8f73b90420c0e4b88b662afb90def8848fcbe2708b5286e186f528"
SRC_URI[deb1.md5sum] = "ee64b5b1cfd21a7dc1ac1a6aac504ac6"
DEBFILENAME_libglib2.0-data = "libglib2.0-data_2.58.3-2+deb10u3_all.deb"
SRC_URI[deb2.sha256sum] = "bc04bacc04c1cec8908d61ccbd801cb079541aeb28443fc961c177c62fa5ae88"
SRC_URI[deb2.md5sum] = "e2c0dc94952ee3e82359bf4069593c92"
DEBFILENAME_libglib2.0-dev = "libglib2.0-dev_2.58.3-2+deb10u3_armhf.deb"
SRC_URI[deb3.sha256sum] = "a1d267f0b9b9d00cf526783411019e2b4b57b349026f1ebd09adfb7e1b234717"
SRC_URI[deb3.md5sum] = "0b5ddf80e94dad2aa6b8c7a23a1674e5"
DEBFILENAME_libglib2.0-dev-bin = "libglib2.0-dev-bin_2.58.3-2+deb10u3_armhf.deb"
SRC_URI[deb4.sha256sum] = "62385df1519519d3b33972e0a10e725958a6c7654c5652ee82e4b57a98680ea1"
SRC_URI[deb4.md5sum] = "d3939f9ceeacf6d335748a3b2d5a7b0f"

RDEPENDS_lib${PN}-0 = "libc6 (>= 2.28) libffi6 (>= 3.0.4) libmount1 (>= 2.28) libpcre3 libselinux1 (>= 1.32) zlib1g (>= 1:1.2.2)"
RDEPENDS_lib${PN}-bin = "libc6 (>= 2.4) libelf1 (>= 0.142) libglib2.0-0 (= 2.58.3-2+deb10u3) libglib2.0-data"
RDEPENDS_lib${PN}-data = ""
RDEPENDS_lib${PN}-dev = "libffi-dev (>= 3.0.0) libglib2.0-0 (= 2.58.3-2+deb10u3) libglib2.0-bin (= 2.58.3-2+deb10u3) libglib2.0-dev-bin (= 2.58.3-2+deb10u3) libmount-dev (>= 2.28) libpcre3-dev (>= 1:8.31) libselinux1-dev pkg-config zlib1g-dev"
RDEPENDS_lib${PN}-dev-bin = "libc6 (>= 2.28) libglib2.0-0 (>= 2.39.4) python3 python3-distutils"
DEPENDS = "libc6 libelf1 libffi-dev libffi6 libmount-dev libmount1 libpcre3 libpcre3-dev libselinux1 libselinux1-dev pkg-config python3 python3-distutils zlib1g zlib1g-dev"


inherit deb_group

FILES_libglib2.0-0 = " \
    ./usr/lib/arm-linux-gnueabihf/glib-2.0/gio-launch-desktop \
    ./usr/lib/arm-linux-gnueabihf/glib-2.0/gio-querymodules \
    ./usr/lib/arm-linux-gnueabihf/glib-2.0/glib-compile-schemas \
    ./usr/lib/arm-linux-gnueabihf/libgio-2.0.so.0 \
    ./usr/lib/arm-linux-gnueabihf/libgio-2.0.so.0.5800.3 \
    ./usr/lib/arm-linux-gnueabihf/libglib-2.0.so.0 \
    ./usr/lib/arm-linux-gnueabihf/libglib-2.0.so.0.5800.3 \
    ./usr/lib/arm-linux-gnueabihf/libgmodule-2.0.so.0 \
    ./usr/lib/arm-linux-gnueabihf/libgmodule-2.0.so.0.5800.3 \
    ./usr/lib/arm-linux-gnueabihf/libgobject-2.0.so.0 \
    ./usr/lib/arm-linux-gnueabihf/libgobject-2.0.so.0.5800.3 \
    ./usr/lib/arm-linux-gnueabihf/libgthread-2.0.so.0 \
    ./usr/lib/arm-linux-gnueabihf/libgthread-2.0.so.0.5800.3 \
    ./usr/share/doc/libglib2.0-0/NEWS.gz \
    ./usr/share/doc/libglib2.0-0/README.md.gz \
    ./usr/share/doc/libglib2.0-0/changelog.Debian.gz \
    ./usr/share/doc/libglib2.0-0/copyright \
    ./usr/share/lintian/overrides/libglib2.0-0\
"
FILES_libglib2.0-bin = " \
    ./usr/bin/gapplication \
    ./usr/bin/gdbus \
    ./usr/bin/gio \
    ./usr/bin/gio-querymodules \
    ./usr/bin/glib-compile-schemas \
    ./usr/bin/gresource \
    ./usr/bin/gsettings \
    ./usr/share/bash-completion/completions/gapplication \
    ./usr/share/bash-completion/completions/gdbus \
    ./usr/share/bash-completion/completions/gio \
    ./usr/share/bash-completion/completions/gresource \
    ./usr/share/bash-completion/completions/gsettings \
    ./usr/share/doc/libglib2.0-bin/changelog.Debian.gz \
    ./usr/share/doc/libglib2.0-bin/copyright \
    ./usr/share/lintian/overrides/libglib2.0-bin \
    ./usr/share/man/man1/gapplication.1.gz \
    ./usr/share/man/man1/gdbus.1.gz \
    ./usr/share/man/man1/gio-querymodules.1.gz \
    ./usr/share/man/man1/gio.1.gz \
    ./usr/share/man/man1/glib-compile-schemas.1.gz \
    ./usr/share/man/man1/gresource.1.gz \
    ./usr/share/man/man1/gsettings.1.gz\
"
FILES_libglib2.0-data = " \
    ./usr/share/doc/libglib2.0-data/changelog.Debian.gz \
    ./usr/share/doc/libglib2.0-data/copyright \
    ./usr/share/locale/af/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/am/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/an/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/ar/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/as/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/ast/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/az/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/be/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/be@latin/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/bg/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/bn/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/bn_IN/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/bs/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/ca/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/ca@valencia/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/cs/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/cy/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/da/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/de/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/dz/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/el/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/en@shaw/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/en_CA/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/en_GB/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/eo/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/es/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/et/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/eu/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/fa/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/fi/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/fr/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/fur/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/ga/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/gd/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/gl/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/gu/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/he/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/hi/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/hr/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/hu/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/hy/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/id/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/is/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/it/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/ja/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/ka/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/kk/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/kn/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/ko/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/ku/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/lt/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/lv/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/mai/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/mg/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/mk/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/ml/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/mn/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/mr/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/ms/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/nb/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/nds/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/ne/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/nl/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/nn/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/oc/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/or/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/pa/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/pl/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/ps/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/pt/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/pt_BR/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/ro/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/ru/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/rw/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/si/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/sk/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/sl/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/sq/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/sr/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/sr@ije/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/sr@latin/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/sv/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/ta/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/te/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/tg/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/th/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/tl/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/tr/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/tt/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/ug/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/uk/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/vi/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/wa/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/xh/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/yi/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/zh_CN/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/zh_HK/LC_MESSAGES/glib20.mo \
    ./usr/share/locale/zh_TW/LC_MESSAGES/glib20.mo\
"
FILES_libglib2.0-dev = " \
    ./usr/include/gio-unix-2.0/gio/gdesktopappinfo.h \
    ./usr/include/gio-unix-2.0/gio/gfiledescriptorbased.h \
    ./usr/include/gio-unix-2.0/gio/gunixconnection.h \
    ./usr/include/gio-unix-2.0/gio/gunixcredentialsmessage.h \
    ./usr/include/gio-unix-2.0/gio/gunixfdlist.h \
    ./usr/include/gio-unix-2.0/gio/gunixfdmessage.h \
    ./usr/include/gio-unix-2.0/gio/gunixinputstream.h \
    ./usr/include/gio-unix-2.0/gio/gunixmounts.h \
    ./usr/include/gio-unix-2.0/gio/gunixoutputstream.h \
    ./usr/include/gio-unix-2.0/gio/gunixsocketaddress.h \
    ./usr/include/glib-2.0/gio/gaction.h \
    ./usr/include/glib-2.0/gio/gactiongroup.h \
    ./usr/include/glib-2.0/gio/gactiongroupexporter.h \
    ./usr/include/glib-2.0/gio/gactionmap.h \
    ./usr/include/glib-2.0/gio/gappinfo.h \
    ./usr/include/glib-2.0/gio/gapplication.h \
    ./usr/include/glib-2.0/gio/gapplicationcommandline.h \
    ./usr/include/glib-2.0/gio/gasyncinitable.h \
    ./usr/include/glib-2.0/gio/gasyncresult.h \
    ./usr/include/glib-2.0/gio/gbufferedinputstream.h \
    ./usr/include/glib-2.0/gio/gbufferedoutputstream.h \
    ./usr/include/glib-2.0/gio/gbytesicon.h \
    ./usr/include/glib-2.0/gio/gcancellable.h \
    ./usr/include/glib-2.0/gio/gcharsetconverter.h \
    ./usr/include/glib-2.0/gio/gcontenttype.h \
    ./usr/include/glib-2.0/gio/gconverter.h \
    ./usr/include/glib-2.0/gio/gconverterinputstream.h \
    ./usr/include/glib-2.0/gio/gconverteroutputstream.h \
    ./usr/include/glib-2.0/gio/gcredentials.h \
    ./usr/include/glib-2.0/gio/gdatagrambased.h \
    ./usr/include/glib-2.0/gio/gdatainputstream.h \
    ./usr/include/glib-2.0/gio/gdataoutputstream.h \
    ./usr/include/glib-2.0/gio/gdbusactiongroup.h \
    ./usr/include/glib-2.0/gio/gdbusaddress.h \
    ./usr/include/glib-2.0/gio/gdbusauthobserver.h \
    ./usr/include/glib-2.0/gio/gdbusconnection.h \
    ./usr/include/glib-2.0/gio/gdbuserror.h \
    ./usr/include/glib-2.0/gio/gdbusinterface.h \
    ./usr/include/glib-2.0/gio/gdbusinterfaceskeleton.h \
    ./usr/include/glib-2.0/gio/gdbusintrospection.h \
    ./usr/include/glib-2.0/gio/gdbusmenumodel.h \
    ./usr/include/glib-2.0/gio/gdbusmessage.h \
    ./usr/include/glib-2.0/gio/gdbusmethodinvocation.h \
    ./usr/include/glib-2.0/gio/gdbusnameowning.h \
    ./usr/include/glib-2.0/gio/gdbusnamewatching.h \
    ./usr/include/glib-2.0/gio/gdbusobject.h \
    ./usr/include/glib-2.0/gio/gdbusobjectmanager.h \
    ./usr/include/glib-2.0/gio/gdbusobjectmanagerclient.h \
    ./usr/include/glib-2.0/gio/gdbusobjectmanagerserver.h \
    ./usr/include/glib-2.0/gio/gdbusobjectproxy.h \
    ./usr/include/glib-2.0/gio/gdbusobjectskeleton.h \
    ./usr/include/glib-2.0/gio/gdbusproxy.h \
    ./usr/include/glib-2.0/gio/gdbusserver.h \
    ./usr/include/glib-2.0/gio/gdbusutils.h \
    ./usr/include/glib-2.0/gio/gdrive.h \
    ./usr/include/glib-2.0/gio/gdtlsclientconnection.h \
    ./usr/include/glib-2.0/gio/gdtlsconnection.h \
    ./usr/include/glib-2.0/gio/gdtlsserverconnection.h \
    ./usr/include/glib-2.0/gio/gemblem.h \
    ./usr/include/glib-2.0/gio/gemblemedicon.h \
    ./usr/include/glib-2.0/gio/gfile.h \
    ./usr/include/glib-2.0/gio/gfileattribute.h \
    ./usr/include/glib-2.0/gio/gfileenumerator.h \
    ./usr/include/glib-2.0/gio/gfileicon.h \
    ./usr/include/glib-2.0/gio/gfileinfo.h \
    ./usr/include/glib-2.0/gio/gfileinputstream.h \
    ./usr/include/glib-2.0/gio/gfileiostream.h \
    ./usr/include/glib-2.0/gio/gfilemonitor.h \
    ./usr/include/glib-2.0/gio/gfilenamecompleter.h \
    ./usr/include/glib-2.0/gio/gfileoutputstream.h \
    ./usr/include/glib-2.0/gio/gfilterinputstream.h \
    ./usr/include/glib-2.0/gio/gfilteroutputstream.h \
    ./usr/include/glib-2.0/gio/gicon.h \
    ./usr/include/glib-2.0/gio/ginetaddress.h \
    ./usr/include/glib-2.0/gio/ginetaddressmask.h \
    ./usr/include/glib-2.0/gio/ginetsocketaddress.h \
    ./usr/include/glib-2.0/gio/ginitable.h \
    ./usr/include/glib-2.0/gio/ginputstream.h \
    ./usr/include/glib-2.0/gio/gio-autocleanups.h \
    ./usr/include/glib-2.0/gio/gio.h \
    ./usr/include/glib-2.0/gio/gioenums.h \
    ./usr/include/glib-2.0/gio/gioenumtypes.h \
    ./usr/include/glib-2.0/gio/gioerror.h \
    ./usr/include/glib-2.0/gio/giomodule.h \
    ./usr/include/glib-2.0/gio/gioscheduler.h \
    ./usr/include/glib-2.0/gio/giostream.h \
    ./usr/include/glib-2.0/gio/giotypes.h \
    ./usr/include/glib-2.0/gio/glistmodel.h \
    ./usr/include/glib-2.0/gio/gliststore.h \
    ./usr/include/glib-2.0/gio/gloadableicon.h \
    ./usr/include/glib-2.0/gio/gmemoryinputstream.h \
    ./usr/include/glib-2.0/gio/gmemoryoutputstream.h \
    ./usr/include/glib-2.0/gio/gmenu.h \
    ./usr/include/glib-2.0/gio/gmenuexporter.h \
    ./usr/include/glib-2.0/gio/gmenumodel.h \
    ./usr/include/glib-2.0/gio/gmount.h \
    ./usr/include/glib-2.0/gio/gmountoperation.h \
    ./usr/include/glib-2.0/gio/gnativevolumemonitor.h \
    ./usr/include/glib-2.0/gio/gnetworkaddress.h \
    ./usr/include/glib-2.0/gio/gnetworking.h \
    ./usr/include/glib-2.0/gio/gnetworkmonitor.h \
    ./usr/include/glib-2.0/gio/gnetworkservice.h \
    ./usr/include/glib-2.0/gio/gnotification.h \
    ./usr/include/glib-2.0/gio/goutputstream.h \
    ./usr/include/glib-2.0/gio/gpermission.h \
    ./usr/include/glib-2.0/gio/gpollableinputstream.h \
    ./usr/include/glib-2.0/gio/gpollableoutputstream.h \
    ./usr/include/glib-2.0/gio/gpollableutils.h \
    ./usr/include/glib-2.0/gio/gpropertyaction.h \
    ./usr/include/glib-2.0/gio/gproxy.h \
    ./usr/include/glib-2.0/gio/gproxyaddress.h \
    ./usr/include/glib-2.0/gio/gproxyaddressenumerator.h \
    ./usr/include/glib-2.0/gio/gproxyresolver.h \
    ./usr/include/glib-2.0/gio/gremoteactiongroup.h \
    ./usr/include/glib-2.0/gio/gresolver.h \
    ./usr/include/glib-2.0/gio/gresource.h \
    ./usr/include/glib-2.0/gio/gseekable.h \
    ./usr/include/glib-2.0/gio/gsettings.h \
    ./usr/include/glib-2.0/gio/gsettingsbackend.h \
    ./usr/include/glib-2.0/gio/gsettingsschema.h \
    ./usr/include/glib-2.0/gio/gsimpleaction.h \
    ./usr/include/glib-2.0/gio/gsimpleactiongroup.h \
    ./usr/include/glib-2.0/gio/gsimpleasyncresult.h \
    ./usr/include/glib-2.0/gio/gsimpleiostream.h \
    ./usr/include/glib-2.0/gio/gsimplepermission.h \
    ./usr/include/glib-2.0/gio/gsimpleproxyresolver.h \
    ./usr/include/glib-2.0/gio/gsocket.h \
    ./usr/include/glib-2.0/gio/gsocketaddress.h \
    ./usr/include/glib-2.0/gio/gsocketaddressenumerator.h \
    ./usr/include/glib-2.0/gio/gsocketclient.h \
    ./usr/include/glib-2.0/gio/gsocketconnectable.h \
    ./usr/include/glib-2.0/gio/gsocketconnection.h \
    ./usr/include/glib-2.0/gio/gsocketcontrolmessage.h \
    ./usr/include/glib-2.0/gio/gsocketlistener.h \
    ./usr/include/glib-2.0/gio/gsocketservice.h \
    ./usr/include/glib-2.0/gio/gsrvtarget.h \
    ./usr/include/glib-2.0/gio/gsubprocess.h \
    ./usr/include/glib-2.0/gio/gsubprocesslauncher.h \
    ./usr/include/glib-2.0/gio/gtask.h \
    ./usr/include/glib-2.0/gio/gtcpconnection.h \
    ./usr/include/glib-2.0/gio/gtcpwrapperconnection.h \
    ./usr/include/glib-2.0/gio/gtestdbus.h \
    ./usr/include/glib-2.0/gio/gthemedicon.h \
    ./usr/include/glib-2.0/gio/gthreadedsocketservice.h \
    ./usr/include/glib-2.0/gio/gtlsbackend.h \
    ./usr/include/glib-2.0/gio/gtlscertificate.h \
    ./usr/include/glib-2.0/gio/gtlsclientconnection.h \
    ./usr/include/glib-2.0/gio/gtlsconnection.h \
    ./usr/include/glib-2.0/gio/gtlsdatabase.h \
    ./usr/include/glib-2.0/gio/gtlsfiledatabase.h \
    ./usr/include/glib-2.0/gio/gtlsinteraction.h \
    ./usr/include/glib-2.0/gio/gtlspassword.h \
    ./usr/include/glib-2.0/gio/gtlsserverconnection.h \
    ./usr/include/glib-2.0/gio/gvfs.h \
    ./usr/include/glib-2.0/gio/gvolume.h \
    ./usr/include/glib-2.0/gio/gvolumemonitor.h \
    ./usr/include/glib-2.0/gio/gzlibcompressor.h \
    ./usr/include/glib-2.0/gio/gzlibdecompressor.h \
    ./usr/include/glib-2.0/glib-object.h \
    ./usr/include/glib-2.0/glib-unix.h \
    ./usr/include/glib-2.0/glib.h \
    ./usr/include/glib-2.0/glib/deprecated/gallocator.h \
    ./usr/include/glib-2.0/glib/deprecated/gcache.h \
    ./usr/include/glib-2.0/glib/deprecated/gcompletion.h \
    ./usr/include/glib-2.0/glib/deprecated/gmain.h \
    ./usr/include/glib-2.0/glib/deprecated/grel.h \
    ./usr/include/glib-2.0/glib/deprecated/gthread.h \
    ./usr/include/glib-2.0/glib/galloca.h \
    ./usr/include/glib-2.0/glib/garray.h \
    ./usr/include/glib-2.0/glib/gasyncqueue.h \
    ./usr/include/glib-2.0/glib/gatomic.h \
    ./usr/include/glib-2.0/glib/gbacktrace.h \
    ./usr/include/glib-2.0/glib/gbase64.h \
    ./usr/include/glib-2.0/glib/gbitlock.h \
    ./usr/include/glib-2.0/glib/gbookmarkfile.h \
    ./usr/include/glib-2.0/glib/gbytes.h \
    ./usr/include/glib-2.0/glib/gcharset.h \
    ./usr/include/glib-2.0/glib/gchecksum.h \
    ./usr/include/glib-2.0/glib/gconvert.h \
    ./usr/include/glib-2.0/glib/gdataset.h \
    ./usr/include/glib-2.0/glib/gdate.h \
    ./usr/include/glib-2.0/glib/gdatetime.h \
    ./usr/include/glib-2.0/glib/gdir.h \
    ./usr/include/glib-2.0/glib/genviron.h \
    ./usr/include/glib-2.0/glib/gerror.h \
    ./usr/include/glib-2.0/glib/gfileutils.h \
    ./usr/include/glib-2.0/glib/ggettext.h \
    ./usr/include/glib-2.0/glib/ghash.h \
    ./usr/include/glib-2.0/glib/ghmac.h \
    ./usr/include/glib-2.0/glib/ghook.h \
    ./usr/include/glib-2.0/glib/ghostutils.h \
    ./usr/include/glib-2.0/glib/gi18n-lib.h \
    ./usr/include/glib-2.0/glib/gi18n.h \
    ./usr/include/glib-2.0/glib/giochannel.h \
    ./usr/include/glib-2.0/glib/gkeyfile.h \
    ./usr/include/glib-2.0/glib/glib-autocleanups.h \
    ./usr/include/glib-2.0/glib/glist.h \
    ./usr/include/glib-2.0/glib/gmacros.h \
    ./usr/include/glib-2.0/glib/gmain.h \
    ./usr/include/glib-2.0/glib/gmappedfile.h \
    ./usr/include/glib-2.0/glib/gmarkup.h \
    ./usr/include/glib-2.0/glib/gmem.h \
    ./usr/include/glib-2.0/glib/gmessages.h \
    ./usr/include/glib-2.0/glib/gnode.h \
    ./usr/include/glib-2.0/glib/goption.h \
    ./usr/include/glib-2.0/glib/gpattern.h \
    ./usr/include/glib-2.0/glib/gpoll.h \
    ./usr/include/glib-2.0/glib/gprimes.h \
    ./usr/include/glib-2.0/glib/gprintf.h \
    ./usr/include/glib-2.0/glib/gqsort.h \
    ./usr/include/glib-2.0/glib/gquark.h \
    ./usr/include/glib-2.0/glib/gqueue.h \
    ./usr/include/glib-2.0/glib/grand.h \
    ./usr/include/glib-2.0/glib/grcbox.h \
    ./usr/include/glib-2.0/glib/grefcount.h \
    ./usr/include/glib-2.0/glib/grefstring.h \
    ./usr/include/glib-2.0/glib/gregex.h \
    ./usr/include/glib-2.0/glib/gscanner.h \
    ./usr/include/glib-2.0/glib/gsequence.h \
    ./usr/include/glib-2.0/glib/gshell.h \
    ./usr/include/glib-2.0/glib/gslice.h \
    ./usr/include/glib-2.0/glib/gslist.h \
    ./usr/include/glib-2.0/glib/gspawn.h \
    ./usr/include/glib-2.0/glib/gstdio.h \
    ./usr/include/glib-2.0/glib/gstrfuncs.h \
    ./usr/include/glib-2.0/glib/gstring.h \
    ./usr/include/glib-2.0/glib/gstringchunk.h \
    ./usr/include/glib-2.0/glib/gtestutils.h \
    ./usr/include/glib-2.0/glib/gthread.h \
    ./usr/include/glib-2.0/glib/gthreadpool.h \
    ./usr/include/glib-2.0/glib/gtimer.h \
    ./usr/include/glib-2.0/glib/gtimezone.h \
    ./usr/include/glib-2.0/glib/gtrashstack.h \
    ./usr/include/glib-2.0/glib/gtree.h \
    ./usr/include/glib-2.0/glib/gtypes.h \
    ./usr/include/glib-2.0/glib/gunicode.h \
    ./usr/include/glib-2.0/glib/gurifuncs.h \
    ./usr/include/glib-2.0/glib/gutils.h \
    ./usr/include/glib-2.0/glib/guuid.h \
    ./usr/include/glib-2.0/glib/gvariant.h \
    ./usr/include/glib-2.0/glib/gvarianttype.h \
    ./usr/include/glib-2.0/glib/gversion.h \
    ./usr/include/glib-2.0/glib/gversionmacros.h \
    ./usr/include/glib-2.0/glib/gwin32.h \
    ./usr/include/glib-2.0/gmodule.h \
    ./usr/include/glib-2.0/gobject/gbinding.h \
    ./usr/include/glib-2.0/gobject/gboxed.h \
    ./usr/include/glib-2.0/gobject/gclosure.h \
    ./usr/include/glib-2.0/gobject/genums.h \
    ./usr/include/glib-2.0/gobject/glib-types.h \
    ./usr/include/glib-2.0/gobject/gmarshal.h \
    ./usr/include/glib-2.0/gobject/gobject-autocleanups.h \
    ./usr/include/glib-2.0/gobject/gobject.h \
    ./usr/include/glib-2.0/gobject/gobjectnotifyqueue.c \
    ./usr/include/glib-2.0/gobject/gparam.h \
    ./usr/include/glib-2.0/gobject/gparamspecs.h \
    ./usr/include/glib-2.0/gobject/gsignal.h \
    ./usr/include/glib-2.0/gobject/gsourceclosure.h \
    ./usr/include/glib-2.0/gobject/gtype.h \
    ./usr/include/glib-2.0/gobject/gtypemodule.h \
    ./usr/include/glib-2.0/gobject/gtypeplugin.h \
    ./usr/include/glib-2.0/gobject/gvalue.h \
    ./usr/include/glib-2.0/gobject/gvaluearray.h \
    ./usr/include/glib-2.0/gobject/gvaluecollector.h \
    ./usr/include/glib-2.0/gobject/gvaluetypes.h \
    ./usr/lib/arm-linux-gnueabihf/glib-2.0/include/glibconfig.h \
    ./usr/lib/arm-linux-gnueabihf/libgio-2.0.a \
    ./usr/lib/arm-linux-gnueabihf/libgio-2.0.so \
    ./usr/lib/arm-linux-gnueabihf/libglib-2.0.a \
    ./usr/lib/arm-linux-gnueabihf/libglib-2.0.so \
    ./usr/lib/arm-linux-gnueabihf/libgmodule-2.0.a \
    ./usr/lib/arm-linux-gnueabihf/libgmodule-2.0.so \
    ./usr/lib/arm-linux-gnueabihf/libgobject-2.0.a \
    ./usr/lib/arm-linux-gnueabihf/libgobject-2.0.so \
    ./usr/lib/arm-linux-gnueabihf/libgthread-2.0.a \
    ./usr/lib/arm-linux-gnueabihf/libgthread-2.0.so \
    ./usr/lib/arm-linux-gnueabihf/pkgconfig/gio-2.0.pc \
    ./usr/lib/arm-linux-gnueabihf/pkgconfig/gio-unix-2.0.pc \
    ./usr/lib/arm-linux-gnueabihf/pkgconfig/glib-2.0.pc \
    ./usr/lib/arm-linux-gnueabihf/pkgconfig/gmodule-2.0.pc \
    ./usr/lib/arm-linux-gnueabihf/pkgconfig/gmodule-export-2.0.pc \
    ./usr/lib/arm-linux-gnueabihf/pkgconfig/gmodule-no-export-2.0.pc \
    ./usr/lib/arm-linux-gnueabihf/pkgconfig/gobject-2.0.pc \
    ./usr/lib/arm-linux-gnueabihf/pkgconfig/gthread-2.0.pc \
    ./usr/share/doc/libglib2.0-dev/README.Debian \
    ./usr/share/doc/libglib2.0-dev/changelog.Debian.gz \
    ./usr/share/doc/libglib2.0-dev/copyright \
    ./usr/share/gdb/auto-load/usr/lib/arm-linux-gnueabihf/libglib-2.0.so.0.5800.3-gdb.py \
    ./usr/share/gdb/auto-load/usr/lib/arm-linux-gnueabihf/libgobject-2.0.so.0.5800.3-gdb.py \
    ./usr/share/gettext/its/gschema.its \
    ./usr/share/gettext/its/gschema.loc \
    ./usr/share/glib-2.0/gdb/glib_gdb.py \
    ./usr/share/glib-2.0/gdb/gobject_gdb.py \
    ./usr/share/glib-2.0/schemas/gschema.dtd \
    ./usr/share/glib-2.0/valgrind/glib.supp \
    ./usr/share/lintian/overrides/libglib2.0-dev\
"
FILES_libglib2.0-dev-bin = " \
    ./usr/bin/gdbus-codegen \
    ./usr/bin/glib-compile-resources \
    ./usr/bin/glib-genmarshal \
    ./usr/bin/glib-gettextize \
    ./usr/bin/glib-mkenums \
    ./usr/bin/gobject-query \
    ./usr/bin/gtester \
    ./usr/bin/gtester-report \
    ./usr/share/aclocal/glib-2.0.m4 \
    ./usr/share/aclocal/glib-gettext.m4 \
    ./usr/share/aclocal/gsettings.m4 \
    ./usr/share/doc/libglib2.0-dev-bin/changelog.Debian.gz \
    ./usr/share/doc/libglib2.0-dev-bin/copyright \
    ./usr/share/glib-2.0/codegen/__init__.py \
    ./usr/share/glib-2.0/codegen/codegen.py \
    ./usr/share/glib-2.0/codegen/codegen_docbook.py \
    ./usr/share/glib-2.0/codegen/codegen_main.py \
    ./usr/share/glib-2.0/codegen/config.py \
    ./usr/share/glib-2.0/codegen/dbustypes.py \
    ./usr/share/glib-2.0/codegen/parser.py \
    ./usr/share/glib-2.0/codegen/utils.py \
    ./usr/share/glib-2.0/gettext/po/Makefile.in.in \
    ./usr/share/man/man1/gdbus-codegen.1.gz \
    ./usr/share/man/man1/glib-compile-resources.1.gz \
    ./usr/share/man/man1/glib-genmarshal.1.gz \
    ./usr/share/man/man1/glib-gettextize.1.gz \
    ./usr/share/man/man1/glib-mkenums.1.gz \
    ./usr/share/man/man1/gobject-query.1.gz \
    ./usr/share/man/man1/gtester-report.1.gz \
    ./usr/share/man/man1/gtester.1.gz \
    ./usr/share/python3/runtime.d/libglib2.0-dev-bin.rtupdate\
"
